language: python
python:
  - "3.6"
  - "3.7"

services:
  - mysql

# install requirements
install:
  - pip3 install -r requirements.txt

before_install:
  - mysql -e 'CREATE DATABASE `testdb`;'
  - mysql testdb < mysql/main_db_bootstrap.py

script:
  - python -m unittest discover tests/
