language: python
python:
  - "3.6"
  - "3.7"

services:
  - mysql

# install requirements
install:
  - pip3 install -r requirements.txt

before_install:
  - mysql -e 'CREATE DATABASE `testdb`;'
  - mysql -e 'CREATE USER oleksii@localhost IDENTIFIED BY "1";'
  - mysql -e 'GRANT ALL PRIVILEGES ON testdb.* TO oleksii@localhost;'
  - mysql testdb < mysql/main_db_bootstrap.sql

script:
  - python RESTful
  - python -m unittest discover tests/
